resolvers += Resolver.bintrayIvyRepo("hmrc", "sbt-plugin-releases")
resolvers += Resolver.bintrayRepo("hmrc", "releases")
resolvers += Resolver.typesafeRepo("releases")

addSbtPlugin("uk.gov.hmrc"               % "sbt-auto-build"     % "3.0.0")
addSbtPlugin("uk.gov.hmrc"               % "sbt-git-versioning" % "2.2.0")
addSbtPlugin("uk.gov.hmrc"               % "sbt-distributables" % "2.1.0")
addSbtPlugin("com.typesafe.play"         % "sbt-plugin"         % "2.8.8")
addSbtPlugin("org.irundaia.sbt"          % "sbt-sassify"        % "1.4.11")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"    % "2.4.10")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.4.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"       % "0.9.24")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"      % "1.6.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.1.16")
